### ISSUE TITLE
Remove unused header element

### ISSUE THREAD

**Issue by vegetasrevenge** [mark-rebecca/mark-rebecca#1]
https://github.com/mark-rebecca/mark-rebecca/blob/a3faee283cd65bfcc2da595fc8b32948fda9fbf7/codeup-design.html#L33-L36

**Comment by MarkCodes347** [comment]
Hi Vegetasrevenge!
Thank you for contributing the issue, we have looked at it and believe we have resolved it.
Please take a look, thank you!

If it is not resolved, feel free to open another issue and we will take a look! 

Mark
