### ISSUE TITLE
Featured Product

### ISSUE THREAD

**Issue by vegetasrevenge** [mark-rebecca/mark-rebecca#3]
For this card, you need to add a closing div tag after line 105.

This is a good format for the featured product cards, you need to place lines 96-104 within another div which will group it together as one card. Then, make 3 more just like it. 

Then, those 4 featured product cards go into a container together along with the 'Selected Work' as the first element of that container.

Once you have that, make another container for 'The Last' section (seen in the lg/xl mockup) and place the elements needed within. 

The 'Featured Products' and 'The Last' containers should go within a larger container with a bootstrap row class and each will be  a column within

https://github.com/mark-rebecca/mark-rebecca/blob/a3faee283cd65bfcc2da595fc8b32948fda9fbf7/codeup-design.html#L94-L106

**Comment by MarkCodes347** [comment]
Hi Vegetasrevenge! 
Thank you for contributing the issue, we have looked at it and believe we have resolved it. 
Please take a look, thank you!
- Mark

**Comment by MarkCodes347** [comment]
Feel free to open the issue again if it is not resolved! Thank you again!
- Mark
